# Generated by Django 5.1.6 on 2025-03-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
